#!/usr/bin/env python3
"""
Environment Variable Configuration Setup
Helps users set up their .env file for GLM-Grounding skill
"""

import sys
from pathlib import Path
from typing import Optional


def _get_skill_root() -> Path:
    """Get the skill root directory"""
    # Get the directory where this script is located
    script_dir = Path(__file__).resolve().parent
    return script_dir.parent


def _get_env_path(skill_root: Optional[Path] = None) -> Path:
    """Get the path to the .env file"""
    if skill_root is None:
        skill_root = _get_skill_root()
    return skill_root / ".env"


def _env_exists(skill_root: Optional[Path] = None) -> bool:
    """Check if .env file exists"""
    return _get_env_path(skill_root).exists()


def _read_env_file(skill_root: Optional[Path] = None) -> dict:
    """
    Read existing .env file and return as dictionary

    Returns:
        Dictionary of environment variables
    """
    env_path = _get_env_path(skill_root)
    env_vars = {}

    if not env_path.exists():
        return env_vars

    with open(env_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            # Skip comments and empty lines
            if not line or line.startswith("#"):
                continue
            # Parse KEY=VALUE
            if "=" in line:
                key, value = line.split("=", 1)
                env_vars[key.strip()] = value.strip()

    return env_vars


def _write_env_file(env_vars: dict, skill_root: Optional[Path] = None) -> None:
    """
    Write environment variables to .env file

    Args:
        env_vars: Dictionary of environment variables to write
        skill_root: Skill root directory path
    """
    env_path = _get_env_path(skill_root)

    with open(env_path, "w", encoding="utf-8") as f:
        # Write header
        f.write("# GLM-V API Configuration\n")
        f.write("# Auto-generated by config_setup.py\n")
        f.write("# DO NOT commit this file to version control\n\n")

        # Write environment variables
        for key, value in env_vars.items():
            f.write(f"{key}={value}\n")


def _setup_interactive() -> dict:
    """
    Interactive setup for environment variables

    Returns:
        Dictionary of configured environment variables
    """
    env_vars = {}
    existing = _read_env_file()

    print("=" * 60)
    print("GLM-Grounding Skill - Environment Configuration")
    print("=" * 60)
    print()

    # API Key
    current_key = existing.get("ZHIPU_API_KEY", "")
    if current_key:
        print(f"Current API Key: {current_key[:8]}...{current_key[-4:]}")

    api_key = input(
        f"Enter GLM-V API Key{' (press Enter to keep current)' if current_key else ''}: "
    ).strip()

    if not api_key and current_key:
        api_key = current_key
    elif not api_key and not current_key:
        print("Error: API Key is required!")
        sys.exit(1)

    env_vars["ZHIPU_API_KEY"] = api_key

    print()
    print("=" * 60)
    print("Configuration Summary:")
    print("=" * 60)
    print(
        f"API Key: {env_vars['ZHIPU_API_KEY'][:8]}...{env_vars['ZHIPU_API_KEY'][-4:]}"
    )
    print()

    return env_vars


def _setup_from_args(api_key: str) -> dict:
    """
    Setup environment variables from command line arguments

    Args:
        api_key: GLM-V API key
        api_url: Optional API URL

    Returns:
        Dictionary of environment variables
    """
    env_vars = {"ZHIPU_API_KEY": api_key}
    return env_vars


def _validate_config(env_vars: dict) -> bool:
    """
    Validate the configuration

    Args:
        env_vars: Dictionary of environment variables

    Returns:
        True if valid, False otherwise
    """
    if "ZHIPU_API_KEY" not in env_vars or not env_vars["ZHIPU_API_KEY"]:
        print("Error: ZHIPU_API_KEY is required")
        return False

    api_key = env_vars["ZHIPU_API_KEY"]
    if len(api_key) < 10:
        print("Warning: API key seems too short")

    return True


def _show_config() -> None:
    """Display current configuration"""
    env_path = _get_env_path()

    if not env_path.exists():
        print("No .env file found. Run 'setup' to create one.")
        return

    env_vars = _read_env_file()

    if not env_vars:
        print(".env file exists but is empty.")
        return

    print("Current Configuration:")
    print("=" * 60)

    for key, value in env_vars.items():
        if "KEY" in key or "SECRET" in key or "TOKEN" in key:
            # Show only partial value for security
            if len(value) > 12:
                display = f"{value[:8]}...{value[-4:]}"
            else:
                display = "***"
        else:
            display = value
        print(f"{key} = {display}")

    print("=" * 60)


def main():
    """Main CLI interface"""
    import argparse

    parser = argparse.ArgumentParser(
        description="Configure environment variables for GLM-Grounding skill",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Interactive setup
  python config_setup.py setup

  # Setup with arguments
  python config_setup.py setup --api-key YOUR_KEY

  # Show current configuration
  python config_setup.py show
        """,
    )

    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    # Setup command
    setup_parser = subparsers.add_parser(
        "setup", help="Set up environment configuration"
    )
    setup_parser.add_argument("--api-key", "-k", help="GLM-V API key")
    setup_parser.add_argument(
        "--non-interactive",
        "-n",
        action="store_true",
        help="Non-interactive mode (requires --api-key)",
    )

    # Show command
    subparsers.add_parser("show", help="Show current configuration")

    # Validate command
    subparsers.add_parser("validate", help="Validate current configuration")

    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        sys.exit(1)

    skill_root = _get_skill_root()

    if args.command == "setup":
        # Get configuration
        if args.api_key:
            env_vars = _setup_from_args(args.api_key)
        elif args.non_interactive:
            print("Error: --api-key is required in non-interactive mode")
            sys.exit(1)
        else:
            env_vars = _setup_interactive()

        # Validate
        if not _validate_config(env_vars):
            sys.exit(1)

        # Write to .env
        _write_env_file(env_vars, skill_root)

        print()
        print(f"Configuration saved to: {_get_env_path(skill_root)}")
        print()

        # Remind about .gitignore
        gitignore_path = skill_root / ".gitignore"
        if gitignore_path.exists():
            with open(gitignore_path, "r") as f:
                gitignore_content = f.read()
            if ".env" not in gitignore_content:
                print("Tip: Add '.env' to your .gitignore to keep API keys secure")
        else:
            print("Tip: Create a .gitignore file with '.env' to keep API keys secure")

    elif args.command == "show":
        _show_config()

    elif args.command == "validate":
        env_vars = _read_env_file(skill_root)

        if not env_vars:
            print("No configuration found. Run 'setup' first.")
            sys.exit(1)

        print("Validating configuration...")
        if _validate_config(env_vars):
            print("Configuration is valid!")
        else:
            print("Configuration is invalid!")
            sys.exit(1)


if __name__ == "__main__":
    main()
